name: iceraven

on: workflow_dispatch

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: wget https://api.github.com/repos/fork-maintainers/iceraven-browser/releases/latest && wget "$(grep -rioh 'http.*arm64.*.apk')" && wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.2.1/uber-apk-signer-1.2.1.jar && mkdir -p iceraven && unzip *.apk -d iceraven && find . -iname "readerview" -execdir rm -rf {} \; ; cd iceraven && zip -1 -r iceraven.apk . && mv iceraven.apk .. && cd .. && java -jar uber-apk-signer-1.2.1.jar -a iceraven.apk
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release
          files: iceraven-aligned-debugSigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
